using OpenTK.Mathematics;
using System;
using System.Collections.Generic;
using System.Xml.Linq;

namespace OrbitalSimOpenGL
{
    internal static class Colors
    {
        /// <summary>
        /// Get a Color4 given a color name
        /// </summary>
        /// <param name="cName">Case insensitive</param>
        /// <param name="c4"></param>
        /// <remarks>
        /// Use switch rather than a Dictionary
        /// 1. This is infrequently used so the linear search is OK
        /// 2. Lazy allocation, dict would instantiate every color whether used or not
        /// </remarks>
        public static void GetColor4(String cName, out Color4 c4)
        {
            c4 = cName.ToUpper() switch
            {
                "ALICEBLUE" => Color4.AliceBlue,
                "ANTIQUEWHITE" => Color4.AntiqueWhite,
                "AQUA" => Color4.Aqua,
                "AQUAMARINE" => Color4.Aquamarine,
                "AZURE" => Color4.Azure,
                "BEIGE" => Color4.Beige,
                "Bisque" => Color4.Bisque,
                "BLACK" => Color4.Black,
                "BLANCHEDALMOND" => Color4.BlanchedAlmond,
                "BLUE" => Color4.Blue,
                "BLUEVIOLET" => Color4.BlueViolet,
                "BROWN" => Color4.Brown,
                "BURLYWOOD" => Color4.BurlyWood,
                "CADETBLUE" => Color4.CadetBlue,
                "CHARTREUSE" => Color4.Chartreuse,
                "CHOCOLATE" => Color4.Chocolate,
                "CORAL" => Color4.Coral,
                "CORNFLOWERBLUE" => Color4.CornflowerBlue,
                "CORNSILK" => Color4.Cornsilk,
                "CRIMSON" => Color4.Crimson,
                "CYAN" => Color4.Cyan,
                "DARKBLUE" => Color4.DarkBlue,
                "DARKCYAN" => Color4.DarkCyan,
                "DARKGOLDENROD" => Color4.DarkGoldenrod,
                "DARKGRAY" => Color4.DarkGray,
                "DARKGREEN" => Color4.DarkGreen,
                "DARKKHAKI" => Color4.DarkKhaki,
                "DARKMAGENTA" => Color4.DarkMagenta,
                "DARKOLIVEGREEN" => Color4.DarkOliveGreen,
                "DARKORANGE" => Color4.DarkOrange,
                "DARKORCHID" => Color4.DarkOrchid,
                "DARKRED" => Color4.DarkRed,
                "DARKSALMON" => Color4.DarkSalmon,
                "DARKSEAGREEN" => Color4.DarkSeaGreen,
                "DARKSLATEBLUE" => Color4.DarkSlateBlue,
                "DARKSLATEGRAY" => Color4.DarkSlateGray,
                "DARKTURQUOISE" => Color4.DarkTurquoise,
                "DARKVIOLET" => Color4.DarkViolet,
                "DEEPPINK" => Color4.DeepPink,
                "DEEPSKYBLUE" => Color4.DeepSkyBlue,
                "DIMGRAY" => Color4.DimGray,
                "DODGERBLUE" => Color4.DodgerBlue,
                "FIREBRICK" => Color4.Firebrick,
                "FLORALWHITE" => Color4.FloralWhite,
                "FORESTGREEN" => Color4.ForestGreen,
                "FUCHSIA" => Color4.Fuchsia,
                "GAINSBORO" => Color4.Gainsboro,
                "GHOSTWHITE" => Color4.GhostWhite,
                "GOLD" => Color4.Gold,
                "GOLDENROD" => Color4.Goldenrod,
                "GRAY" => Color4.Gray,
                "GREEN" => Color4.Green,
                "GREENYELLOW" => Color4.GreenYellow,
                "HONEYDEW" => Color4.Honeydew,
                "HOTPINK" => Color4.HotPink,
                "INDIANRED" => Color4.IndianRed,
                "INDIGO" => Color4.Indigo,
                "IVORY" => Color4.Ivory,
                "KHAKI" => Color4.Khaki,
                "LAVENDER" => Color4.Lavender,
                "LAVENDERBLUSH" => Color4.LavenderBlush,
                "LAWNGREEN" => Color4.LawnGreen,
                "LEMONCHIFFON" => Color4.LemonChiffon,
                "LIGHTBLUE" => Color4.LightBlue,
                "LIGHTCORAL" => Color4.LightCoral,
                "LIGHTCYAN" => Color4.LightCyan,
                "LIGHTGOLDENRODYELLOW" => Color4.LightGoldenrodYellow,
                "LIGHTGRAY" => Color4.LightGray,
                "LIGHTGREEN" => Color4.LightGreen,
                "LIGHTPINK" => Color4.LightPink,
                "LIGHTSALMON" => Color4.LightSalmon,
                "LIGHTSEAGREEN" => Color4.LightSeaGreen,
                "LIGHTSKYBLUE" => Color4.LightSkyBlue,
                "LIGHTSLATEGRAY" => Color4.LightSlateGray,
                "LIGHTSTEELBLUE" => Color4.LightSteelBlue,
                "LIGHTYELLOW" => Color4.LightYellow,
                "LIME" => Color4.Lime,
                "LIMEGREEN" => Color4.LimeGreen,
                "LINEN" => Color4.Linen,
                "MAGENTA" => Color4.Magenta,
                "MAROON" => Color4.Maroon,
                "MEDIUMAQUAMARINE" => Color4.MediumAquamarine,
                "MEDIUMBLUE" => Color4.MediumBlue,
                "MEDIUMORCHID" => Color4.MediumOrchid,
                "MEDIUMPURPLE" => Color4.MediumPurple,
                "MEDIUMSEAGREEN" => Color4.MediumSeaGreen,
                "MEDIUMSLATEBLUE" => Color4.MediumSlateBlue,
                "MEDIUMSPRINGGREEN" => Color4.MediumSpringGreen,
                "MEDIUMTURQUOISE" => Color4.MediumTurquoise,
                "MEDIUMVIOLETRED" => Color4.MediumVioletRed,
                "MIDNIGHTBLUE" => Color4.MidnightBlue,
                "MINTCREAM" => Color4.MintCream,
                "MISTYROSE" => Color4.MistyRose,
                "MOCCASIN" => Color4.Moccasin,
                "NAVAJOWHITE" => Color4.NavajoWhite,
                "NAVY" => Color4.Navy,
                "OLDLACE" => Color4.OldLace,
                "OLIVE" => Color4.Olive,
                "OLIVEDRAB" => Color4.OliveDrab,
                "ORANGE" => Color4.Orange,
                "ORANGERED" => Color4.OrangeRed,
                "ORCHID" => Color4.Orchid,
                "PALEGOLDENROD" => Color4.PaleGoldenrod,
                "PALEGREEN" => Color4.PaleGreen,
                "PALETURQUOISE" => Color4.PaleTurquoise,
                "PALEVIOLETRED" => Color4.PaleVioletRed,
                "PAPAYAWHIP" => Color4.PapayaWhip,
                "PEACHPUFF" => Color4.PeachPuff,
                "PERU" => Color4.Peru,
                "PINK" => Color4.Pink,
                "PLUM" => Color4.Plum,
                "POWDERBLUE" => Color4.PowderBlue,
                "PURPLE" => Color4.Purple,
                "RED" => Color4.Red,
                "ROSYBROWN" => Color4.RosyBrown,
                "ROYALBLUE" => Color4.RoyalBlue,
                "SADDLEBROWN" => Color4.SaddleBrown,
                "SALMON" => Color4.Salmon,
                "SANDYBROWN" => Color4.SandyBrown,
                "SEAGREEN" => Color4.SeaGreen,
                "SEASHELL" => Color4.SeaShell,
                "SIENNA" => Color4.Sienna,
                "SILVER" => Color4.Silver,
                "SKYBLUE" => Color4.SkyBlue,
                "SLATEBLUE" => Color4.SlateBlue,
                "SLATEGRAY" => Color4.SlateGray,
                "SNOW" => Color4.Snow,
                "SPRINGGREEN" => Color4.SpringGreen,
                "STEELBLUE" => Color4.SteelBlue,
                "TAN" => Color4.Tan,
                "TEAL" => Color4.Teal,
                "THISTLE" => Color4.Thistle,
                "TOMATO" => Color4.Tomato,
                "TRANSPARENT" => Color4.Transparent,
                "TURQUOISE" => Color4.Turquoise,
                "VIOLET" => Color4.Violet,
                "WHEAT" => Color4.Wheat,
                "WHITE" => Color4.White,
                "WHITESMOKE" => Color4.WhiteSmoke,
                "YELLOW" => Color4.Yellow,
                "YELLOWGREEN" => Color4.YellowGreen,
                _ => Color4.Black
            };
        }
    }
}
